### ISSUE TITLE
Conditionally ignore an embedded list

### ISSUE THREAD

**Issue by akhilesh-bangalore** [danbarua/Nancy.Hal#13]
When a list is embedded in the HAL response, it is displayed even when it is empty. 

It will be useful to expose a predicate argument (like the Links method) on the embeds method of HalTypeConfiguration<T> so that it could be added/igored on the final response conditionally.

**Comment by danbarua** [comment]
:+1:

**Comment by wk001** [comment]
I haven't explicitly tested lists but PR #19 should fix this

**Comment by danbarua** [comment]
Yup, this is now in 1.2.0 up on NuGet :+1:
