### ISSUE TITLE
Allow request sensitive configuration

### ISSUE THREAD

**Issue by thomaseizinger** [danbarua/Nancy.Hal#14]
As a developer, I want to add additional configuration on a per request basis in the handler of the request. My idea is to reuse the existing configurarion class, store it in the nancy context with the help of an extension method, pull it out in the response processor and temporarily merge it with the global configuration.

I plan to have a PR for this by tomorrow morning! :)

**Comment by danbarua** [comment]
Coo, look forward to it!

**Comment by danbarua** [comment]
This is in v1.1.0 on NuGet
