### ISSUE TITLE
Clarify existence of files under "Response" folder

### ISSUE THREAD

**Issue by thomaseizinger** [danbarua/Nancy.Hal#16]
While browsing the repo, I stumbled upon the "Response" (https://github.com/danbarua/Nancy.Hal/tree/master/src/Nancy.Hal/Response) folder which contains 3 files, from which one seems to be an older version of the HalJsonResponseProcessor. (which is actually located in the "Processors" folder)

However, these files are excluded from the solution and therefore also do not have any references anywhere in the project. (At least I did not find any.)

At least to me, this was quite irritating.

**Comment by danbarua** [comment]
It's been a while but I suspect this was my quick'n'dirty first implementation before Matt came in and tidied it all up. The code/examples/readme does need a clean up.

**Comment by danbarua** [comment]
Tidied up.
